# Generated by Django 3.2.13 on 2023-03-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='iscustom',
            field=models.BooleanField(default=True),
        ),
    ]
