# Generated by Django 3.2.13 on 2023-03-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_products_iscustom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='iscustom',
            new_name='custom',
        ),
    ]
