# Generated by Django 3.2.13 on 2023-04-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_iscustom_products_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='custom',
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
