# Generated by Django 3.2.13 on 2023-04-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230403_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
