# Generated by Django 3.2.13 on 2023-04-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
